version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"